name: CI Básico

on:
  push:
    branches:
      - 'feature-*'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write  

    strategy:
      matrix:
        include:
        - language: 'javascript-typescript'
          build-mode: 'none'

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Instalar dependencias
        run: npm ci
      
      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
      
      - name: Ejecutar análisis CodeQL
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"